
package gr7372.turkin.lab2;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MathServiceService", targetNamespace = "http://lab2.turkin.gr7372/", wsdlLocation = "http://localhost:8080/math?wsdl")
public class MathServiceService
    extends Service
{

    private final static URL MATHSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(gr7372.turkin.lab2.MathServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = gr7372.turkin.lab2.MathServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/math?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/math?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MATHSERVICESERVICE_WSDL_LOCATION = url;
    }

    public MathServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MathServiceService() {
        super(MATHSERVICESERVICE_WSDL_LOCATION, new QName("http://lab2.turkin.gr7372/", "MathServiceService"));
    }

    /**
     * 
     * @return
     *     returns MathService
     */
    @WebEndpoint(name = "MathServicePort")
    public MathService getMathServicePort() {
        return super.getPort(new QName("http://lab2.turkin.gr7372/", "MathServicePort"), MathService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MathService
     */
    @WebEndpoint(name = "MathServicePort")
    public MathService getMathServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://lab2.turkin.gr7372/", "MathServicePort"), MathService.class, features);
    }

}
